# Version of YAML paired with k8 API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stedi-seth
spec:
# Replicas: number of pods we deploy
  replicas: 1
  selector:
    matchLabels:
      app: stedi-seth
  template:
    metadata:
      labels:
        app: stedi-seth
    spec:
      containers:
        - name: stedi-seth
          image: nginx
          ports:
            - containerPort: 80
          resources:  
            limits:
              cpu: ".125"
              memory: "500Mi"
            requests: 
              cpu: ".125"
              memory: "250Mi"
          livenessProbe: 
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: stedi-seth-loadbalancer
spec:
  selector: 
    app: stedi-seth
  type: LoadBalancer
  ports: 
    - port: 80
      targetPort: 80
      